[tool.pylint.main]
# Python code to execute, usually for sys.path manipulation such as
# pygtk.require().
# init-hook =

# Use multiple processes to speed up Pylint. Specifying 0 will auto-detect the
# number of processors available to use, and will cap the count on Windows to
# avoid hangs.
jobs = 0

[tool.pylint.format]
# String used as indentation unit. This is usually "    " (4 spaces) or "\t" (1 tab).
indent-string = "\t"

# Maximum number of characters on a single line.
max-line-length = 150
